stages:
#- run-script
#- show-variable
- terraform-validate
- terraform-plan
# - terraform-apply-staging
# - terraform-apply-production

# run-script:
#   stage: run-script
#   image: ubuntu
#   script:
#   - bash pipeline/scripts/hello.sh

# show-variable:
#   stage: show-variable
#   image: ubuntu
#   script:
#   - bash pipeline/scripts/show-variable.sh

terraform-validate:
  stage: terraform-validate
  image: johnmorsley/alpine-with-terraform
  script:
  - ls -la
  - cd terraform
  - export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
  - export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
  - printenv
#  - terraform init -backend-config="token=$TERRAFORM_CLOUD_TOKEN"
#  - terraform validate

terraform-plan:
  stage: terraform-plan
  image: johnmorsley/alpine-with-terraform
  script:
  - ls -la
  - cd terraform
  - export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
  - export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
  - printenv
#  - terraform init -backend-config="token=$TERRAFORM_CLOUD_TOKEN"
#  - terraform plan

# terraform-apply-staging:
#   stage: terraform-apply-staging
#   image: hashicorp/terraform:0.13.5
#   script:
#   - terraform apply --auto-approve
  
# terraform-apply-production:
#   stage: terraform-apply-production
#   image: hashicorp/terraform:0.13.5
#   script:
#   - terrasform apply --auto-approve