stages:
- run-script
- show-variable
#- terraform-validate
# - terraform-plan
# - terraform-apply-staging
# - terraform-apply-production

run-script:
  stage: run-script
  image: ubuntu
  script:
  - bash pipeline/scripts/hello.sh

show-variable:
  stage: show-variable
  image: ubuntu
  script:
  - bash pipeline/scripts/show-variable.sh

terraform-validate:
  stage: terraform-validate
  image: johnmorsley/alpine-with-terraform
#  before_script:
#  - ls -la
  script:
  - ls -la
  - cd terraform
  - export TF_VAR_terraform_cloud_token=$TERRAFORM_CLOUD_TOKEN
  - terraform init 
  - terraform validate

# terraform-plan:
#   stage: terraform-plan
#   image: hashicorp/terraform:0.13.5
#   script:
#   - terraform plan

# terraform-apply-staging:
#   stage: terraform-apply-staging
#   image: hashicorp/terraform:0.13.5
#   script:
#   - terraform apply --auto-approve
  
# terraform-apply-production:
#   stage: terraform-apply-production
#   image: hashicorp/terraform:0.13.5
#   script:
#   - terrasform apply --auto-approve