stages:
#- run-script
#- show-variable
- terraform-validate
- terraform-plan
- terraform-apply
# - terraform-apply-production

# run-script:
#   stage: run-script
#   image: ubuntu
#   script:
#   - bash pipeline/scripts/hello.sh

# show-variable:
#   stage: show-variable
#   image: ubuntu
#   script:
#   - bash pipeline/scripts/show-variable.sh

terraform-validate:
  stage: terraform-validate
  image: johnmorsley/alpine-with-terraform
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  script:
  - ls -la
  - cd terraform
  - terraform init -backend-config="token=$TERRAFORM_CLOUD_TOKEN"
  - terraform validate

terraform-plan:
  stage: terraform-plan
  image: johnmorsley/alpine-with-terraform
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  script:
  - ls -la
  - cd terraform
  - terraform init -backend-config="token=$TERRAFORM_CLOUD_TOKEN"
  - terraform plan

terraform-apply:
  stage: terraform-apply
  image: johnmorsley/alpine-with-terraform
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  script:
  - ls -la
  - cd terraform
  - terraform init -backend-config="token=$TERRAFORM_CLOUD_TOKEN"
  - terraform apply --auto-approve

# terraform-apply-staging:
#   stage: terraform-apply-staging
#   image: hashicorp/terraform:0.13.5
#   script:
#   - terraform apply --auto-approve
  
# terraform-apply-production:
#   stage: terraform-apply-production
#   image: hashicorp/terraform:0.13.5
#   script:
#   - terrasform apply --auto-approve