stages:
#- run-script
#- show-variable
- terraform-validate
- terraform-plan
- terraform-apply
- terraform-destroy

# run-script:
#   stage: run-script
#   image: ubuntu
#   script:
#   - bash pipeline/scripts/hello.sh

# show-variable:
#   stage: show-variable
#   image: ubuntu
#   script:
#   - bash pipeline/scripts/show-variable.sh

terraform-validate:
  stage: terraform-validate
  image: johnmorsley/alpine-with-terraform
#  variables:
#    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
#    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
#    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  script:
  - cd terraform
  - terraform init -backend-config="token=$TERRAFORM_CLOUD_TOKEN"
  - terraform validate

terraform-plan:
  stage: terraform-plan
  image: johnmorsley/alpine-with-terraform
  variables:
    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  script:
  - cd terraform
  - terraform init -backend-config="token=$TERRAFORM_CLOUD_TOKEN"
  - terraform plan

terraform-apply:
  stage: terraform-apply
  image: johnmorsley/alpine-with-terraform
  variables:
    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  script:
  - cd terraform
  - terraform init -backend-config="token=$TERRAFORM_CLOUD_TOKEN"
  - terraform apply --auto-approve

terraform-destroy:
  stage: terraform-destroy
  image: johnmorsley/alpine-with-terraform
  variables:
    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  script:
  - cd terraform
  - terraform init -backend-config="token=$TERRAFORM_CLOUD_TOKEN"
  - terraform destroy --auto-approve  