stages:
- run-script
- terraform-verify
# - terraform-plan
# - terraform-apply-staging
# - terraform-apply-production

run-script:
  stage: run-script
  image: ubuntu
  script:
  - bash pipeline/scripts/hello.sh

terraform-verify:
  stage: terraform-verify
  image: hashicorp/terraform:full
  script:
  - ls -la
#  - bash pipeline/scripts/hello.sh
#  - cd terraform
#  - terraform validate

# terraform-plan:
#   stage: terraform-plan
#   image: hashicorp/terraform:0.13.5
#   script:
#   - terraform plan

# terraform-apply-staging:
#   stage: terraform-apply-staging
#   image: hashicorp/terraform:0.13.5
#   script:
#   - terraform apply --auto-approve
  
# terraform-apply-production:
#   stage: terraform-apply-production
#   image: hashicorp/terraform:0.13.5
#   script:
#   - terrasform apply --auto-approve